jupyter_book_task:
  only_if: $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH || $CIRRUS_BASE_BRANCH == $CIRRUS_DEFAULT_BRANCH
  env:
    JOBS: '8'
    GH_TOKEN: ENCRYPTED[a866156d0f45b8f6e45ef8621656d89b794669aa57571dd3b0202e7cdc70f1ae21bf1799f17f1d58ee96b525d497cbb4]
  auto_cancellation: true
  container:
    dockerfile: julia.Dockerfile
    cpu: 4
    memory: 16G
    greedy: true
  notebook_script: |
    parallel --joblog /tmp/log -j${JOBS} jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --execute --inplace {} ::: docs/*.ipynb
    cat /tmp/log
  build_script: |
    jupyter-book build docs/ --keep-going -v
  # Requires a repo scope access `GH_TOKEN` PAT to push
  pages_script: |
    if [[ $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH ]]; then
      git remote set-url origin https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git
      ghp-import -n -p -f docs/_build/html
    fi
