name: Auto update Julia dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every week

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
    uses: sosiristseng/jbook-workflows/.github/workflows/update-manifest.yml@main
    with:
      julia-version: "~1.9.0-rc2"
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
